### ISSUE TITLE
Object parts in PACO-EGO4D

### ISSUE THREAD

**Issue by simeonjunker** [facebookresearch/paco#21]
In the PACO-EGO4D test split, there are no object part annotations for any of the items (i.e. everything in the file `paco_ego4d_v1_test_dev.json` is annotated as "supercategory: OBJECT"). Both the train and the test split contain object part annotations.
Is that on purpose? Are the part annotations available somewhere?

**Comment by vpetrovi** [comment]
Thanks for your interest in our dataset. We have withheld test annotations for PACO zero-shot challenge (https://eval.ai/web/challenges/challenge-page/1970/overview). Since the challenge is over, we are releasing the full test dataset. Please download the dataset again and you should see all the annotations.
